### ISSUE TITLE
Does not compile on DOIT ESP32 DEVKIT V1

### ISSUE THREAD

**Issue by untitledlt** [PRosenb/DeepSleepScheduler#7]
I'm using Arduino IDE.
Followed installation instructions from readme.
What am i doing wrong?

> In file included from /Users/untitled/Documents/Arduino/libraries/DeepSleepScheduler/DeepSleepScheduler.h:573:0,
                 from /Users/untitled/workplace/esp32/deepSleep/deepSleep/deepSleep.ino:2:
/Users/untitled/Documents/Arduino/libraries/DeepSleepScheduler/DeepSleepScheduler_esp.h: In static member function 'static void SchedulerEsp::isrWatchdogExpiredStatic()':
/Users/untitled/Documents/Arduino/libraries/DeepSleepScheduler/DeepSleepScheduler_esp.h:77:20: error: 'esp_restart_noos' was not declared in this scope
   esp_restart_noos();
                    ^
exit status 1
Error compiling for board DOIT ESP32 DEVKIT V1.

**Comment by PRosenb** [comment]
Thanks for pointing that out @untitledlt , this function was removed.
I adjusted `DeepSleepScheduler` and published the new version 3.0.1. Please let me know if it works now.
