### ISSUE TITLE
multiple definition of '****'

### ISSUE THREAD

**Issue by Fires04** [PRosenb/DeepSleepScheduler#8]
Hi, I try your library in my project but I got problem to compile it.
I use VS Code with Platform.io.

> Linking .pioenvs\esp12e\firmware.elf
> .pioenvs\esp12e\src\configuration.cpp.o: In function `SchedulerEsp::taskWdtDisable()':
> configuration.cpp:(.text._ZN12SchedulerEsp14taskWdtDisableEv+0x8): multiple definition of `SchedulerEsp::taskWdtDisable()'
> .pioenvs\esp12e\src\callbackFunctions.cpp.o:callbackFunctions.cpp:(.text._ZN12SchedulerEsp14taskWdtDisableEv+0x8): first defined here
> .pioenvs\esp12e\src\configuration.cpp.o: In function `SchedulerEsp::taskWdtReset()':
> configuration.cpp:(.text._ZN12SchedulerEsp12taskWdtResetEv+0x8): multiple definition of `SchedulerEsp::taskWdtReset()'
> .pioenvs\esp12e\src\callbackFunctions.cpp.o:callbackFunctions.cpp:(.text._ZN12SchedulerEsp12taskWdtResetEv+0x8): first defined here
> .pioenvs\esp12e\src\configuration.cpp.o: In function `SchedulerEsp::taskWdtEnable(unsigned char)':
> configuration.cpp:(.text._ZN12SchedulerEsp13taskWdtEnableEh+0xc): multiple definition of `SchedulerEsp::taskWdtEnable(unsigned char)'
> .pioenvs\esp12e\src\callbackFunctions.cpp.o:callbackFunctions.cpp:(.text._ZN12SchedulerEsp13taskWdtEnableEh+0xc): first defined here
> .pioenvs\esp12e\src\configuration.cpp.o: In function `SchedulerEsp::sleepIfRequired()':
> configuration.cpp:(.text._ZN12SchedulerEsp15sleepIfRequiredEv+0x8): multiple definition of `SchedulerEsp::sleepIfRequired()'
> .pioenvs\esp12e\src\callbackFunctions.cpp.o:callbackFunctions.cpp:(.text._ZN12SchedulerEsp15sleepIfRequiredEv+0x8): first defined here
> .pioenvs\esp12e\src\configuration.cpp.o: In function `Scheduler::Scheduler()':
> configuration.cpp:(.text._ZN9SchedulerC2Ev+0x4): multiple definition of `Scheduler::Scheduler()'
> .pioenvs\esp12e\src\callbackFunctions.cpp.o:callbackFunctions.cpp:(.text._ZN9SchedulerC2Ev+0x4): first defined here
> .pioenvs\esp12e\src\configuration.cpp.o: In function `Scheduler::Scheduler()':
> configuration.cpp:(.text._ZN9SchedulerC2Ev+0x4): multiple definition of `Scheduler::Scheduler()'
> .pioenvs\esp12e\src\callbackFunctions.cpp.o:callbackFunctions.cpp:(.text._ZN9SchedulerC2Ev+0x4): first defined here
> .pioenvs\esp12e\src\configuration.cpp.o: In function `Scheduler::scheduleAtFrontOfQueue(void (*)())':

Any suggest?

my includes.h

> `/**
>  * Includes file include all required libraries
>  */ 
> #ifndef INCLUDES_H
> #define INCLUDES_H
> 
> #include <ESP8266WiFi.h>
> #ifdef USE_MDNS
>   #include <DNSServer.h>
>   #include <ESP8266mDNS.h>
> #endif
>   #ifdef WEB_SERVER_ENABLED
>     #include <ESP8266WebServer.h>
> #endif
> 
> // Arduino OTA
> #ifdef USE_ARDUINO_OTA
>   #include <ArduinoOTA.h>
> #endif
> 
> //Other Libraries
> #include <jled.h>
> #include <EasyBuzzer.h>
> #include <ESP8266HTTPClient.h>
> #include <WiFiClient.h>
> #include <DeepSleepScheduler.h>
> 
> 
> #endif //INCLUDES_H `

**Comment by PRosenb** [comment]
Hi @Fires04 , 
The header file `DeepSleepScheduler.h` can only be included once. If you need to include the definitions of `DeepSleepScheduler.h` multiple times, you need to define `LIBCALL_DEEP_SLEEP_SCHEDULER` before each include of `DeepSleepScheduler.h` except one. Please see [Implementation Notes](https://github.com/PRosenb/DeepSleepScheduler#general-1).

Exactly once:
```c++
#include <DeepSleepScheduler.h>
```
Multiple times:
```c++
#define LIBCALL_DEEP_SLEEP_SCHEDULER
#include <DeepSleepScheduler.h>
```
Does this solve your issue?
